### ISSUE TITLE
WMF save handler not installed

### ISSUE THREAD

**Issue by sohahia** [gasongjian/reportgen#1]
在运行第一个实例的时候出错。请问这该怎么解决？谢谢[1，Get texts or images in a pptx file.](https://github.com/gasongjian/reportgen/blob/master/README.rst)
Traceback (most recent call last):
  File "e:\PY_reportgen\Easy_demo\demo1.py", line 9, in <module>
    p.get_images()
  File "D:\Python3\lib\site-packages\reportgen\report.py", line 810, in get_images
    p.save(filename)
  File "D:\Python3\lib\site-packages\PIL\Image.py", line 1826, in save
    save_handler(self, fp, filename)
  File "D:\Python3\lib\site-packages\PIL\WmfImagePlugin.py", line 157, in _save
    raise IOError("WMF save handler not installed")
OSError: WMF save handler not installed

**Comment by gasongjian** [comment]
看文字，貌似是PIL包的WMF没有安装
1、建议你升级 PIL（pip install Pillow），或者使用anaconda。
2、reportgen都是在windows的anaconda下测试的，其他平台暂时没有测试过。
